// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"database/sql"
)

type Aturkolom struct {
	Kode                 sql.NullString
	Tpenjualan           sql.NullString
	Tpembelian           sql.NullString
	Thutang              sql.NullString
	Tpiutang             sql.NullString
	Tbiaya               sql.NullString
	Tcashflow            sql.NullString
	Treturpenjualan      sql.NullString
	Treturpembelian      sql.NullString
	Dobat                sql.NullString
	Dsuplier             sql.NullString
	Dpelanggan           sql.NullString
	Dsales               sql.NullString
	Ddokter              sql.NullString
	Dkaryawan            sql.NullString
	Dpetunjuk            sql.NullString
	DobatReq             sql.NullString
	DkaryawanReq         sql.NullString
	Dsaldoawal           sql.NullString
	TpenjualanReq        sql.NullString
	TpembelianReq        sql.NullString
	Psaldoawal           sql.NullString
	Psaldoawalhutang     sql.NullString
	Pstokopname          sql.NullString
	Psaldoawalpiutang    sql.NullString
	TpembelianpendingReq sql.NullString
	TpenjualanpendingReq sql.NullString
	Tpembeliandetail     sql.NullString
	Tpenjualandetail     sql.NullString
	UserID               sql.NullString
}

type Autokode struct {
	ID               sql.NullString
	Obat             sql.NullString
	Suplier          sql.NullString
	Pelanggan        sql.NullString
	Sales            sql.NullString
	Dokter           sql.NullString
	Petunjuk         sql.NullString
	Karyawan         sql.NullString
	Operator         sql.NullString
	Kategori         sql.NullString
	ReturPembelian   sql.NullString
	ReturPenjualan   sql.NullString
	Saldoawal        sql.NullString
	Saldoawalhutang  sql.NullString
	Saldoawalpiutang sql.NullString
	Stokopname       sql.NullString
	NoPesanan        sql.NullString
	UserID           sql.NullString
}

type Barcode struct {
	Kode   sql.NullString
	Nama   sql.NullString
	Harga  sql.NullString
	UserID sql.NullString
}

type Checkboxediting struct {
	Kategori         sql.NullString
	MengubahHarga    sql.NullString
	MengubahTanggal  sql.NullString
	MemberikanDiskon sql.NullString
	UpdateHarga      sql.NullString
	HargaJual        sql.NullString
	LabaOtomatis     sql.NullString
	OptionPrint      sql.NullString
	HargaResep       sql.NullString
	PendingFaktur    sql.NullString
	KonfirmasiObat   sql.NullString
	FormOngkos       sql.NullString
	FormPpn          sql.NullString
	NilaiPpn         sql.NullString
	DiskonFaktur     sql.NullString
	HargaTertinggi   sql.NullString
	PembulatanHarga  sql.NullString
	AngkaPembulatan  sql.NullString
	HargaBeli        sql.NullString
	PrintPreview     sql.NullString
	CentangPpn       sql.NullString
	FakturBaru       sql.NullString
	HargaSebelumnya  sql.NullString
	LabaJual         sql.NullString
	StokMinus        sql.NullString
	InputTabel       string
	UserID           sql.NullString
}

type Comboalasan struct {
	Nama   sql.NullString
	UserID sql.NullString
}

type Comboexpired struct {
	Nama   sql.NullString
	UserID sql.NullString
}

type Combojeniska struct {
	Nama   sql.NullString
	UserID sql.NullString
}

type Combojenispenjualan struct {
	Nama   sql.NullString
	UserID sql.NullString
}

type Combokategoriobat struct {
	Nama   string
	UserID string
}

type Combokategoripemasukan struct {
	Kode   sql.NullString
	Nama   sql.NullString
	UserID sql.NullString
}

type Combokategoripengeluaran struct {
	Kode   sql.NullString
	Nama   sql.NullString
	UserID sql.NullString
}

type Comboresepnonresep struct {
	Nama   sql.NullString
	UserID sql.NullString
}

type Combosatuanbeli struct {
	Nama   string
	UserID string
}

type Combosatuanjual struct {
	Nama   string
	UserID string
}

type Combostok struct {
	Nama   sql.NullString
	UserID sql.NullString
}

type Combotunaikredit struct {
	Nama   sql.NullString
	UserID sql.NullString
}

type Comboukurancetak struct {
	Nama   sql.NullString
	UserID sql.NullString
}

type Dapotek struct {
	Kode                   sql.NullString
	NamaApotek             sql.NullString
	Apoteker               sql.NullString
	Nohp                   sql.NullString
	Alamat                 sql.NullString
	HeaderNota             sql.NullString
	FooterNota             sql.NullString
	KodeOperator           sql.NullString
	LokasiDatabase         sql.NullString
	Logo                   sql.NullString
	NomorWaLapOnline       string
	PasswordLapOnline      string
	SinkronLaporan         string
	NomorWaNotif           string
	ValuePeriode           string
	Pukul                  string
	WaktuKirimPesan        string
	TextHeader             string
	TextTotalHarian        string
	TextTotalBulanan       string
	BanyakTransaksiHarian  string
	BanyakTransaksiBulanan string
	UserID                 sql.NullString
}

type Ddokter struct {
	Kode       string
	Nama       sql.NullString
	Alamat     sql.NullString
	NoHp       sql.NullString
	Email      sql.NullString
	Rekening   sql.NullString
	Keterangan sql.NullString
	UserID     string
}

type Dediting struct {
	Kode                    sql.NullString
	TanggalPembelian        sql.NullString
	HargaPembelian          sql.NullString
	DiskonRefakturPembelian sql.NullString
	TanggalPenjualan        sql.NullString
	HargaPenjualan          sql.NullString
	DiksonRefakturPenjualan sql.NullString
	UserID                  sql.NullString
}

type Dkaryawan struct {
	Kode       sql.NullString
	Nama       sql.NullString
	Alamat     sql.NullString
	NoHp       sql.NullString
	Email      sql.NullString
	Rekening   sql.NullString
	Keterangan sql.NullString
	UserID     sql.NullString
}

type Dobat struct {
	Kode         string
	Nama         sql.NullString
	Kategori     sql.NullString
	Stok         sql.NullString
	SatuanBeli   sql.NullString
	HargaBeli    sql.NullString
	StokMin      sql.NullString
	Satuan1      sql.NullString
	Satuan2      sql.NullString
	Satuan3      sql.NullString
	Satuan4      sql.NullString
	Isi1         sql.NullString
	Isi2         sql.NullString
	Isi3         sql.NullString
	Isi4         sql.NullString
	HargaJual1   sql.NullString
	HargaJual2   sql.NullString
	HargaJual3   sql.NullString
	HargaJual4   sql.NullString
	HargaResep1  sql.NullString
	HargaResep2  sql.NullString
	HargaResep3  sql.NullString
	HargaResep4  sql.NullString
	LabaOtomatis sql.NullString
	Suplier      sql.NullString
	Pabrik       sql.NullString
	Expired      sql.NullString
	Indikasi     sql.NullString
	Komposisi    sql.NullString
	Lokasi       sql.NullString
	NoBatch      sql.NullString
	UserID       string
}

type Doperator struct {
	Kode                   string
	Username               sql.NullString
	Password               sql.NullString
	Apotek                 sql.NullString
	Operator               sql.NullString
	Editing                sql.NullString
	Barcode                sql.NullString
	Persediaan             sql.NullString
	Aktivasi               sql.NullString
	Updates                sql.NullString
	About                  sql.NullString
	ImportSaldoAwal        sql.NullString
	JendelaObat            sql.NullString
	TambahBiaya            sql.NullString
	ExportDokter           sql.NullString
	Piutang                sql.NullString
	HapusKaryawan          sql.NullString
	JendelaPetunjuk        sql.NullString
	ExportSaldoAwal        sql.NullString
	DetailBiaya            sql.NullString
	HapusPelanggan         sql.NullString
	JendelaCashflow        sql.NullString
	HapusSaldoAwal         sql.NullString
	DetailSaldoAwalHutang  sql.NullString
	ExportSuplier          sql.NullString
	TambahHutang           sql.NullString
	CetakPenjualan         sql.NullString
	ImportObat             sql.NullString
	HapusDokter            sql.NullString
	ExportPelanggan        sql.NullString
	DetailPenjualan        sql.NullString
	JendelaSales           sql.NullString
	JendelaPiutang         sql.NullString
	JendelaHutang          sql.NullString
	BayarHutang            sql.NullString
	TambahSaldoAwalPiutang sql.NullString
	JendelaPenjualan       sql.NullString
	TambahKaryawan         sql.NullString
	DetailSaldoAwalPiutang sql.NullString
	ExportBiaya            sql.NullString
	ExportStokOpname       sql.NullString
	ExportPiutang          sql.NullString
	EditKaryawan           sql.NullString
	HapusPetunjuk          sql.NullString
	TambahStokOpname       sql.NullString
	EditPetunjuk           sql.NullString
	HapusSales             sql.NullString
	JendelaPembelian       sql.NullString
	StokOpname             sql.NullString
	TambahCashflow         sql.NullString
	Hutang                 sql.NullString
	CetakPembelian         sql.NullString
	Laporan                sql.NullString
	ExportPembelian        sql.NullString
	TambahDokter           sql.NullString
	ExportPenjualan        sql.NullString
	HapusPembelian         sql.NullString
	DetailCashflow         sql.NullString
	EditPelanggan          sql.NullString
	Penjualan              sql.NullString
	HapusSuplier           sql.NullString
	HapusHutang            sql.NullString
	HapusBiaya             sql.NullString
	TambahPetunjuk         sql.NullString
	EditSuplier            sql.NullString
	ExportSales            sql.NullString
	Pembelian              sql.NullString
	Pengaturan             sql.NullString
	HapusPenjualan         sql.NullString
	TambahSaldoAwalHutang  sql.NullString
	DetailReturPembelian   sql.NullString
	ExportSaldoAwalHutang  sql.NullString
	EditSales              sql.NullString
	Cashflow               sql.NullString
	ImportDokter           sql.NullString
	TambahSuplier          sql.NullString
	JendelaPelanggan       sql.NullString
	EditObat               sql.NullString
	TambahSales            sql.NullString
	ImportSaldoAwalPiutang sql.NullString
	ExportSaldoAwalPiutang sql.NullString
	JendelaDokter          sql.NullString
	ReturPenjualan         sql.NullString
	TambahReturPembelian   sql.NullString
	ExportHutang           sql.NullString
	ImportSales            sql.NullString
	TambahObat             sql.NullString
	DetailSaldoAwal        sql.NullString
	HapusCashflow          sql.NullString
	JendelaBiaya           sql.NullString
	ExportKaryawan         sql.NullString
	ImportPelanggan        sql.NullString
	HapusReturPembelian    sql.NullString
	HapusPiutang           sql.NullString
	TambahPiutang          sql.NullString
	JendelaKaryawan        sql.NullString
	DetailPembelian        sql.NullString
	TambahPelanggan        sql.NullString
	CetakStokOpname        sql.NullString
	ImportSuplier          sql.NullString
	TambahReturPenjualan   sql.NullString
	ExportCashflow         sql.NullString
	ExportObat             sql.NullString
	CetakPiutang           sql.NullString
	EditDokter             sql.NullString
	CetakBiaya             sql.NullString
	HapusStokOpname        sql.NullString
	ImportPetunjuk         sql.NullString
	CetakHutang            sql.NullString
	HapusSaldoAwalHutang   sql.NullString
	SaldoAwal              sql.NullString
	HapusReturPenjualan    sql.NullString
	ImportKaryawan         sql.NullString
	DetailReturPenjualan   sql.NullString
	TambahSaldoAwal        sql.NullString
	ImportStokOpname       sql.NullString
	HapusSaldoAwalPiutang  sql.NullString
	TambahPenjualan        sql.NullString
	ExportPetunjuk         sql.NullString
	SaldoAwalPiutang       sql.NullString
	CetakCashflow          sql.NullString
	ImportSaldoAwalHutang  sql.NullString
	DetailStokOpname       sql.NullString
	ReturPembelian         sql.NullString
	SaldoAwalHutang        sql.NullString
	JendelaSuplier         sql.NullString
	BayarPiutang           sql.NullString
	TambahPembelian        sql.NullString
	HapusObat              sql.NullString
	AturKolom              sql.NullString
	Printsizename          sql.NullString
	Obat                   sql.NullString
	Laba                   sql.NullString
	ExportPembelianDetail  sql.NullString
	ExportPenjualanDetail  sql.NullString
	Keuangan               sql.NullString
	Aplikasi               sql.NullString
	Printer                sql.NullString
	Printsizenamesp        sql.NullString
	DisplayHarga           sql.NullString
	Online                 sql.NullString
	HistoriHutang          string
	HistoriPiutang         string
	UserID                 string
}

type Dpelanggan struct {
	Kode       string
	Nama       sql.NullString
	Alamat     sql.NullString
	NoHp       sql.NullString
	Email      sql.NullString
	Rekening   sql.NullString
	Keterangan sql.NullString
	UserID     string
}

type Dpetunjuk struct {
	Kode     sql.NullString
	Petunjuk sql.NullString
	UserID   sql.NullString
}

type Dsale struct {
	Kode       string
	Nama       sql.NullString
	Alamat     sql.NullString
	NoHp       sql.NullString
	Email      sql.NullString
	Rekening   sql.NullString
	Keterangan sql.NullString
	UserID     string
}

type Dsuplier struct {
	Kode       string
	Nama       sql.NullString
	Alamat     sql.NullString
	NoHp       sql.NullString
	Email      sql.NullString
	Rekening   sql.NullString
	Keterangan sql.NullString
	UserID     string
}

type Filtertanggal struct {
	Tanggal          sql.NullString
	Pembelian        sql.NullString
	Penjualan        sql.NullString
	Hutang           sql.NullString
	Piutang          sql.NullString
	Biaya            sql.NullString
	Cashflow         sql.NullString
	Returpembelian   sql.NullString
	Returpenjualan   sql.NullString
	Stokopname       sql.NullString
	Saldoawal        sql.NullString
	Saldoawalhutang  sql.NullString
	Saldoawalpiutang sql.NullString
	Pembeliandetail  sql.NullString
	Penjualandetail  sql.NullString
	UserID           sql.NullString
}

type Keluarmasuk struct {
	Faktur     sql.NullString
	Tanggal    sql.NullString
	Kode       sql.NullString
	Nama       sql.NullString
	Masuk      sql.NullString
	Keluar     sql.NullString
	Status     sql.NullString
	Sisa       sql.NullString
	Keterangan sql.NullString
	NoBatch    sql.NullString
	UserID     sql.NullString
}

type Perubahanharga struct {
	Faktur         sql.NullString
	Tanggal        sql.NullString
	Kode           sql.NullString
	Waktu          sql.NullString
	Nama           sql.NullString
	NaikTurun      sql.NullString
	HargaBeliLama  sql.NullString
	HargaBeliBaru  sql.NullString
	HargaJualLama1 sql.NullString
	HargaJualBaru1 sql.NullString
	HargaJualLama2 sql.NullString
	HargaJualBaru2 sql.NullString
	HargaJualLama3 sql.NullString
	HargaJualBaru3 sql.NullString
	HargaJualLama4 sql.NullString
	HargaJualBaru4 sql.NullString
	Operator       sql.NullString
	UserID         sql.NullString
}

type Psaldoawal struct {
	Kode       string
	Tanggal    sql.NullString
	Waktu      sql.NullString
	KodeObat   sql.NullString
	Nama       sql.NullString
	Jumlah     sql.NullString
	Satuan     sql.NullString
	Harga      sql.NullString
	Total      sql.NullString
	Keterangan sql.NullString
	UserID     string
}

type Psaldoawalhutang struct {
	Kode       sql.NullString
	Faktur     sql.NullString
	Tanggal    sql.NullString
	JatuhTempo sql.NullString
	Suplier    sql.NullString
	Jumlah     sql.NullString
	Keterangan sql.NullString
	UserID     sql.NullString
}

type Psaldoawalpiutang struct {
	Kode       sql.NullString
	Faktur     sql.NullString
	Tanggal    sql.NullString
	JatuhTempo sql.NullString
	Pelanggan  sql.NullString
	Jumlah     sql.NullString
	Keterangan sql.NullString
	UserID     sql.NullString
}

type Pstokopname struct {
	Kode         string
	Tanggal      sql.NullString
	Waktu        sql.NullString
	KodeObat     sql.NullString
	Nama         sql.NullString
	Satuan       sql.NullString
	HargaBeli    sql.NullString
	StokKomputer sql.NullString
	StokNyata    sql.NullString
	Selisih      sql.NullString
	TotalSelisih sql.NullString
	Alasan       sql.NullString
	Operator     sql.NullString
	UserID       string
}

type Tbiaya struct {
	Faktur     sql.NullString
	Tanggal    sql.NullString
	Waktu      sql.NullString
	Kategori   sql.NullString
	Total      sql.NullString
	Keterangan sql.NullString
	Operator   sql.NullString
	UserID     sql.NullString
}

type Tcashflow struct {
	Faktur      sql.NullString
	Tanggal     sql.NullString
	Waktu       sql.NullString
	Jenis       sql.NullString
	Kategori    sql.NullString
	Pemasukan   sql.NullString
	Pengeluaran sql.NullString
	Keterangan  sql.NullString
	Operator    sql.NullString
	UserID      sql.NullString
}

type Thutang struct {
	Faktur       string
	Tanggal      sql.NullString
	Waktu        sql.NullString
	Tempo        sql.NullString
	JatuhTempo   sql.NullString
	Suplier      sql.NullString
	TagihanAwal  sql.NullString
	TelahDibayar sql.NullString
	Sisa         sql.NullString
	Operator     sql.NullString
	Status       sql.NullString
	Keterangan   sql.NullString
	TanggalBayar sql.NullString
	UserID       string
}

type Tpembelian struct {
	Faktur       string
	Tanggal      sql.NullString
	Waktu        sql.NullString
	TunaiKredit  sql.NullString
	Nhari        sql.NullString
	JatuhTempo   sql.NullString
	KodeSuplier  sql.NullString
	Suplier      sql.NullString
	Total        sql.NullString
	DiksonPersen sql.NullString
	Diskon       sql.NullString
	Ppn          sql.NullString
	Ongkos       sql.NullString
	Bayar        sql.NullString
	Kembali      sql.NullString
	NoPesanan    sql.NullString
	Operator     sql.NullString
	UserID       string
}

type Tpembeliandetail struct {
	Faktur         sql.NullString
	Tanggal        sql.NullString
	Kode           sql.NullString
	Nama           sql.NullString
	Kategori       sql.NullString
	Jumlah         sql.NullString
	Satuan         sql.NullString
	HargaLama      sql.NullString
	Harga          sql.NullString
	DiskonPersen   sql.NullString
	Diskon         sql.NullString
	Total          sql.NullString
	Isi1           sql.NullString
	Isi2           sql.NullString
	Isi3           sql.NullString
	Isi4           sql.NullString
	Satuan1        sql.NullString
	Satuan2        sql.NullString
	Satuan3        sql.NullString
	Satuan4        sql.NullString
	HargaJual1     sql.NullString
	HargaJual2     sql.NullString
	HargaJual3     sql.NullString
	HargaJual4     sql.NullString
	HargaResep1    sql.NullString
	HargaResep2    sql.NullString
	HargaResep3    sql.NullString
	HargaResep4    sql.NullString
	Suplier        sql.NullString
	Expired        sql.NullString
	NoBatch        sql.NullString
	InputBaru      sql.NullString
	JumlahKonversi sql.NullString
	UserID         sql.NullString
}

type Tpembelianpending struct {
	Faktur       sql.NullString
	Tanggal      sql.NullString
	Waktu        sql.NullString
	TunaiKredit  sql.NullString
	Nhari        sql.NullString
	JatuhTempo   sql.NullString
	KodeSuplier  sql.NullString
	Suplier      sql.NullString
	Total        sql.NullString
	DiksonPersen sql.NullString
	Diskon       sql.NullString
	Ppn          sql.NullString
	Ongkos       sql.NullString
	Bayar        sql.NullString
	Kembali      sql.NullString
	NoPesanan    sql.NullString
	Operator     sql.NullString
	UserID       sql.NullString
}

type Tpembelianpendingdetail struct {
	Faktur         sql.NullString
	Tanggal        sql.NullString
	Kode           sql.NullString
	Nama           sql.NullString
	Kategori       sql.NullString
	Jumlah         sql.NullString
	Satuan         sql.NullString
	HargaLama      sql.NullString
	Harga          sql.NullString
	DiskonPersen   sql.NullString
	Diskon         sql.NullString
	Total          sql.NullString
	Isi1           sql.NullString
	Isi2           sql.NullString
	Isi3           sql.NullString
	Isi4           sql.NullString
	Satuan1        sql.NullString
	Satuan2        sql.NullString
	Satuan3        sql.NullString
	Satuan4        sql.NullString
	HargaJual1     sql.NullString
	HargaJual2     sql.NullString
	HargaJual3     sql.NullString
	HargaJual4     sql.NullString
	HargaResep1    sql.NullString
	HargaResep2    sql.NullString
	HargaResep3    sql.NullString
	HargaResep4    sql.NullString
	Suplier        sql.NullString
	Expired        sql.NullString
	NoBatch        sql.NullString
	InputBaru      sql.NullString
	JumlahKonversi sql.NullString
	UserID         sql.NullString
}

type Tpenjualan struct {
	Faktur         string
	Tanggal        sql.NullString
	Waktu          sql.NullString
	TunaiKredit    sql.NullString
	Nhari          sql.NullString
	JatuhTempo     sql.NullString
	JenisPenjualan sql.NullString
	KodePelanggan  sql.NullString
	Pelanggan      sql.NullString
	Pasien         sql.NullString
	KodeSales      sql.NullString
	Sales          sql.NullString
	KodeDokter     sql.NullString
	Dokter         sql.NullString
	Total          sql.NullString
	DiksonPersen   sql.NullString
	Diskon         sql.NullString
	Ppn            sql.NullString
	Ongkos         sql.NullString
	Bayar          sql.NullString
	Kembali        sql.NullString
	TotalHargaBeli sql.NullString
	TotalLaba      sql.NullString
	Operator       sql.NullString
	UserID         string
}

type Tpenjualandetail struct {
	Faktur         sql.NullString
	Tanggal        sql.NullString
	Kode           sql.NullString
	Nama           sql.NullString
	Jumlah         sql.NullString
	Satuan         sql.NullString
	HargaBeli      sql.NullString
	HargaJualLama  sql.NullString
	Harga          sql.NullString
	Diskon         sql.NullString
	Total          sql.NullString
	Laba           sql.NullString
	JumlahKonversi sql.NullString
	Expired        sql.NullString
	NoBatch        string
	UserID         sql.NullString
}

type Tpenjualanpending struct {
	Faktur         sql.NullString
	Tanggal        sql.NullString
	Waktu          sql.NullString
	TunaiKredit    sql.NullString
	Nhari          sql.NullString
	JatuhTempo     sql.NullString
	JenisPenjualan sql.NullString
	KodePelanggan  sql.NullString
	Pelanggan      sql.NullString
	Pasien         sql.NullString
	KodeSales      sql.NullString
	Sales          sql.NullString
	KodeDokter     sql.NullString
	Dokter         sql.NullString
	Total          sql.NullString
	DiksonPersen   sql.NullString
	Diskon         sql.NullString
	Ppn            sql.NullString
	Ongkos         sql.NullString
	Bayar          sql.NullString
	Kembali        sql.NullString
	TotalHargaBeli sql.NullString
	TotalLaba      sql.NullString
	Operator       sql.NullString
	UserID         sql.NullString
}

type Tpenjualanpendingdetail struct {
	Faktur         sql.NullString
	Tanggal        sql.NullString
	Kode           sql.NullString
	Nama           sql.NullString
	Jumlah         sql.NullString
	Satuan         sql.NullString
	HargaBeli      sql.NullString
	HargaJualLama  sql.NullString
	Harga          sql.NullString
	Diskon         sql.NullString
	Total          sql.NullString
	Laba           sql.NullString
	JumlahKonversi sql.NullString
	Expired        sql.NullString
	NoBatch        string
	UserID         sql.NullString
}

type Tpiutang struct {
	Faktur       string
	Tanggal      sql.NullString
	Waktu        sql.NullString
	Tempo        sql.NullString
	JatuhTempo   sql.NullString
	Pelanggan    sql.NullString
	TagihanAwal  sql.NullString
	TelahDibayar sql.NullString
	Sisa         sql.NullString
	Operator     sql.NullString
	Status       sql.NullString
	Keterangan   sql.NullString
	TanggalBayar sql.NullString
	UserID       string
}

type Treturpembelian struct {
	NoRetur               string
	Faktur                sql.NullString
	Tanggal               sql.NullString
	Waktu                 sql.NullString
	Suplier               sql.NullString
	TotalRetur            sql.NullString
	TotalDibayar          sql.NullString
	TotalMengurangiHutang sql.NullString
	Operator              sql.NullString
	UserID                string
}

type Treturpembeliandetail struct {
	NoRetur sql.NullString
	Faktur  sql.NullString
	Tanggal sql.NullString
	Kode    sql.NullString
	Nama    sql.NullString
	Jumlah  sql.NullString
	Satuan  sql.NullString
	Harga   sql.NullString
	Total   sql.NullString
	UserID  sql.NullString
}

type Treturpenjualan struct {
	NoRetur                string
	Faktur                 sql.NullString
	Tanggal                sql.NullString
	Waktu                  sql.NullString
	Pelanggan              sql.NullString
	TotalRetur             sql.NullString
	TotalDibayar           sql.NullString
	TotalMengurangiPiutang sql.NullString
	Operator               sql.NullString
	UserID                 string
}

type Treturpenjualandetail struct {
	NoRetur sql.NullString
	Faktur  sql.NullString
	Tanggal sql.NullString
	Kode    string
	Nama    sql.NullString
	Jumlah  sql.NullString
	Satuan  sql.NullString
	Harga   sql.NullString
	Total   sql.NullString
	UserID  sql.NullString
}
