// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package dbsqlc

import (
	"context"
	"database/sql"
)

const getMinStock = `-- name: GetMinStock :many
SELECT d.kode, d.nama, CAST(d.stok AS DECIMAL(10, 2)), CAST(d.stok_min AS DECIMAL(10, 2)), d.komposisi FROM dobat d 
WHERE CAST(d.stok AS FLOAT) <= CAST(d.stok_min AS FLOAT)
AND d.stok_min > 0
ORDER BY d.nama
`

type GetMinStockRow struct {
	Kode      string
	Nama      sql.NullString
	DStok     string
	DStokMin  string
	Komposisi sql.NullString
}

func (q *Queries) GetMinStock(ctx context.Context) ([]GetMinStockRow, error) {
	rows, err := q.db.QueryContext(ctx, getMinStock)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMinStockRow
	for rows.Next() {
		var i GetMinStockRow
		if err := rows.Scan(
			&i.Kode,
			&i.Nama,
			&i.DStok,
			&i.DStokMin,
			&i.Komposisi,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
