// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dbsqlc} from '../models';

export function DObat():Promise<Array<dbsqlc.GetMinStockRow>>;

export function Greet(arg1:string):Promise<string>;
